name: Libplanet benchmark (for merge commits)
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Benchmark.Net benchmarks
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on:
      labels: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Download previous benchmark data
      uses: actions/cache@v1
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark
    - name: Run benchmark
      run: dotnet run -p Libplanet.Benchmarks -c Release -- --exporters json --filter '*'

    - name: Store BlockChain benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Benchmark.Net Benchmark
        tool: 'benchmarkdotnet'
        output-file-path: BenchmarkDotNet.Artifacts/results/Libplanet.Benchmarks.BlockChain-report-full-compressed.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true

    - name: Store DataModel benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Benchmark.Net Benchmark
        tool: 'benchmarkdotnet'
        output-file-path: BenchmarkDotNet.Artifacts/results/Libplanet.Benchmarks.DataModel.DataModelBenchmark-report-full-compressed.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true

    - name: Store MineBlock benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Benchmark.Net Benchmark
        tool: 'benchmarkdotnet'
        output-file-path: BenchmarkDotNet.Artifacts/results/Libplanet.Benchmarks.MineBlock-report-full-compressed.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true

    - name: Store Libplanet.Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Benchmark.Net Benchmark
        tool: 'benchmarkdotnet'
        output-file-path: BenchmarkDotNet.Artifacts/results/Libplanet.Benchmarks.Store-report-full-compressed.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true

#    - name: Store Swarm benchmark result
#      uses: rhysd/github-action-benchmark@v1
#      with:
#        name: Benchmark.Net Benchmark
#        tool: 'benchmarkdotnet'
#        output-file-path: BenchmarkDotNet.Artifacts/results/Libplanet.Benchmarks.SwarmBenchmark-report-full-compressed.json
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        auto-push: true

    - name: Copy benchmark results to cache
      run: rm -rf ./cache && cp -R BenchmarkDotNet.Artifacts/results ./cache
