on: [push]
name: push docker image
jobs:
  build_and_push:
    runs-on: ubuntu-16.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build
        run: docker build . -t planetariumhq/libplanet-explorer:git-${{ github.sha }}
      - name: push (publish)
        run: docker push planetariumhq/libplanet-explorer:git-${{ github.sha }}
